version: '3.8'

services:
  hyperliquid-mcp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - HYPERLIQUID_PRIVATE_KEY=${HYPERLIQUID_PRIVATE_KEY}
      - HYPERLIQUID_ACCOUNT_ADDRESS=${HYPERLIQUID_ACCOUNT_ADDRESS}
      - HYPERLIQUID_TESTNET=${HYPERLIQUID_TESTNET:-false}
      - PORT=8080
      - HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s